### ISSUE TITLE
git: schemafy repository is missing git-tag for 0.2.1

### ISSUE THREAD

**Issue by lucab** [Marwes/schemafy#1]
crates.io [reports 0.2.1](https://crates.io/crates/schemafy/0.2.1) as the latest stable release of this package, but I don't see the corresponding git-tag on this repository. Can you please tag the actual commit used when cutting 0.2.1? It would make casual history digging quicker.

**Comment by Marwes** [comment]
That should do it https://github.com/Marwes/schemafy/releases/tag/v0.2.1
