### ISSUE TITLE
Skip serialization of Option::None's

### ISSUE THREAD

**Issue by vadimcn** [Marwes/schemafy#17]
Schemafy should emit `#[serde(skip_serializing_if="Option::is_none")]` for all Option's (unless that field is required, of course).

**Comment by Marwes** [comment]
I think this should take into account how the `Option` is derived, for options created from `anyOf: [<TYPE>, null]` it should probably still omit that attribute

**Comment by vadimcn** [comment]
> I think this should take into account how the Option is derived

Certainly.   This decision should probably be based on the `required` attribute, not on whether  Rust type is an `Option`.

>  for options created from `anyOf: [<TYPE>, null]` it should probably still omit that attribute

Not only that; one might actually argue that your example should be represented as `Option<Option<TYPE>>` (assuming the field is optional), because that sort of schema probably means that a missing attribute and a null mean different things.

**Comment by Marwes** [comment]
> Not only that; one might actually argue that your example should be represented as Option<Option<TYPE>> (assuming the field is optional), because that sort of schema probably means that a missing attribute and a null mean different things.

True, I'd probably still emit it as a single `Option` as that is more likely what the user expects. If someone actually needs the nested `Option` then that can be tackled at that point, perhaps through configuration.
