### ISSUE TITLE
generate: incomplete types due to nested definitions

### ISSUE THREAD

**Issue by lucab** [Marwes/schemafy#2]
It looks like the library is producing incomplete code due to missing types in case of nested definitions.

As a short example, let's take the following JSON schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "nestedtest",
  "type": "object",
  "properties": {
  },
  "required": [
    "top"
  ],
  "definitions": {
    "top": {
      "type": "object",
      "properties": {
        "basic": {
          "type": "string"
        },
        "nested": {
          "$ref": "#/definitions/top/definitions/defnested"
        }
      },
      "definitions": {
        "defnested": {
          "type": "object",
          "properties": {
            "append": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

which produces the following struct:
```
# [ serde ( rename = "top" ) ]
# [ derive ( Clone , PartialEq , Debug , Default , Deserialize , Serialize ) ]
pub struct Top {
    pub basic: Option<String>,
    pub nested: Option<Defnested>,
}
```

However, the library is not generating any corresponding definition for `Defnested`.

**Comment by Marwes** [comment]
I don't think I needed that features so it seems I missed that case :) Shouldn't be to difficult to fix though.

**Comment by mre** [comment]
In the same vein, could we also support external refs?

```json        
"nested": {
   "$ref": "defnested.json"
}
```

This would greatly help me with my current project.

**Comment by Marwes** [comment]
@lucab Released version 0.2.2 which handles nested definitions.

@mre Sure, though that is unfortunately not trivial to add due to some unfortunate implementation details. I may try to do a refactor later this week.

**Comment by lucab** [comment]
@Marwes thanks for the fast reaction, it looks fine from a very quick test! I'll report separately if I hit other corner-cases.

@mre do you ming moving the external-refs request to its own ticket? This one can otherwise be closed from the point of view of the original issue.

**Comment by mre** [comment]
Absolutely. Moved to new issue. 👍

**Comment by lucab** [comment]
Nested-defs support landed, external-refs tracked at https://github.com/Marwes/schemafy/issues/3. Closing this.
