### ISSUE TITLE
What draft(s) of JSON Schema is supported?

### ISSUE THREAD

**Issue by adamvoss** [Marwes/schemafy#5]
JSON Schema is continuing to make revisions and publish new drafts.  I am guessing this is based on Draft 4.  It would be great if which draft were indicated in the README.

**Comment by Marwes** [comment]
It seems to be draft 4 https://github.com/Marwes/schemafy/blob/dd0b4fd39f79a2f6d66db8e81a6388e780e63898/src/schema.json#L2.

I updated the README

**Comment by adamvoss** [comment]
Thanks!
