### ISSUE TITLE
Feature request: Macro/fn to export generated Struct to file

### ISSUE THREAD

**Issue by lcmgh** [Marwes/schemafy#66]
Hi!

I would like to use the macro within build.rs to make it export the generated struct to a file within my `src`.

That way `schemafy` can be included as dev-dependency rather than as regular dependency while also simplifying schema generation without the need of a cli tool. 

Thanks

**Comment by bemyak** [comment]
This is already possible. Here is an example:
https://gitlab.com/bemyak/roll_bot/-/blob/460d6905d035e455d8aa887ba332246e3243bd99/build.rs#L75-89
